version: '3'
services:
  wiremock:
    image: rodolpheche/wiremock:2.30.1
    ports:
      - "9090:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - JAVA_OPTS=-Xmx512m
